apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      role: admin
  template:
    metadata:
      labels:
        role: admin
    spec: 
      containers:
      - name: admin
        image: thefernan/admin_service:latest
        env:
        - name: Oracle_User
          value: "Fernando"
        - name: Oracle_Pass
          value: "201731087"
        - name: Oracle_Dsn
          value: "34.125.193.240/orcl18"

---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    role: admin