apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      role: chat
  template:
    metadata:
      labels:
        role: chat
    spec: 
      containers:
      - name: chat
        image: thefernan/chat_service:latest
        env:
        - name: Oracle_User
          value: "Fernando"
        - name: Oracle_Pass
          value: "201731087"
        - name: Oracle_Dsn
          value: "34.125.193.240/orcl18"

---
apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    role: chat