FROM node:14

RUN mkdir -p /opt/oracle
RUN cd /opt/oracle
RUN wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linuxx64.zip
RUN unzip instantclient-basic-linuxx64.zip
RUN sh -c "echo /opt/oracle/instantclient_21_3 > /etc/ld.so.conf.d/oracle-instantclient.conf"
RUN ldconfig
RUN export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_3:$LD_LIBRARY_PATH

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app
RUN cd 
COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000
CMD ["npm", "run", "forever"]